### ISSUE TITLE
Is this repo obsolete?

### ISSUE THREAD

**Issue by erciccione** [alvinjoelsantos/promo-video#42]
Hi @ajs-xmr i spoke with savandra about how to manage subtitles. Now they can be uploaded directly on youtube using its native way. This work for both videos uploaded on the 'monero' channel and on savandra's one.
Is this repo still needed?

**Comment by ajs-xmr** [comment]
Yes, for two reasons. (1) to keep a record of commits from contributors and (2) if the videos are ever updated, the scripts would be a good starting point.

**Comment by erciccione** [comment]
I fear this could lead to confusion and mismatching versions. For example: now #40 and #41 have been opened and the author could think that the translation will be uploaded on youtube, but they won't unless somebody pick them from here and upload them on youtube. I don't see the point

**Comment by ajs-xmr** [comment]
Yes, that is a valid concern, but I still think having a commit history is important.

This issue might be better suited for Meta to have wider discussion with other maintainers.


On October 26, 2018 9:58:01 AM UTC, erciccione <notifications@github.com> wrote:
>I fear this could lead to confusion and mismatching versions. For
>example: now #40 and #41 have been opened and the author could think
>that the translation will be uploaded on youtube, but they won't unless
>somebody pick them from here and upload them on youtube. I don't see
>the point
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/monero-ecosystem/promo-video/issues/42#issuecomment-433355725

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
